BaSP-TG-15: Controllers and validations Super-Admin
BaSP-m2022/balti-trackgenix-server pull request #16
Opened 2022-05-16 02:03 UTC by CamilaFigue

- Move routes to routes folder

- Update endpoints logic

- Add JOI validations

- Update postman collection

- Delete JSON file

2022-05-16 13:48 UTC, cellamarematias requested changes

2022-05-17 01:40 UTC, nicolascostanza commented on src/controllers/super-admins.js
> +    }
Este if creo no ingresa nunca, si no existe el params, se va al catch

2022-05-17 22:34 UTC, BaltazarCortina1 commented on src/validations/super-admins.js
> +      success: valid.error.details[0].message,
Al final aca deberia ser error en lugar de success. Y deberia ser un booleano, el mensaje va en msg

2022-05-17 22:49 UTC, BaltazarCortina1 requested changes

2022-05-17 22:49 UTC, BaltazarCortina1 commented on src/validations/super-admins.js
> +      success: valid.error.details[0].message,
Lo mismo aca

2022-05-17 22:49 UTC, BaltazarCortina1 commented on TRACKGENIX.postman_collection.json
> +							"raw": "http://localhost:3000/api/super-admin/",
Las rutas de la collection estan desactualizadas, todas tienen /api

2022-05-17 22:49 UTC, BaltazarCortina1 commented on src/controllers/super-admins.js
> +      msg: 'There was an error',
Aca podrias mandar el error (`err`) en el mensaje o en la data, para dar mas informacion sobre que paso.
Lo mismo en los otros catch

2022-05-17 22:49 UTC, BaltazarCortina1 commented on src/controllers/super-admins.js
> +    });
Aca falta la validacion para ver si encontro uno o no

2022-05-17 22:49 UTC, BaltazarCortina1 commented on src/controllers/super-admins.js
> +      });
Esta validacion esta de mas, porque si no le pasas ningun param no entra en esta ruta

2022-05-17 22:49 UTC, BaltazarCortina1 commented on src/controllers/super-admins.js
> +    }
Lo mismo aca, esta validacion no cumple ninguna funcion

2022-05-18 00:37 UTC, BaltazarCortina1 approved these changes

2022-05-18 00:50 UTC, cellamarematias approved these changes

2022-05-18 00:56 UTC, merged