BaSP-TG-26: Create, delete and update employees.
BaSP-m2022/balti-trackgenix-server pull request #18
Opened 2022-05-16 14:48 UTC by cellamarematias

2022-05-17 04:38 UTC, ilcosme commented on src/index.js
> +  createEmployee, deleteEmployee, updateEmployee, filterByDni,
Mati esto ya no es necesario importarlo en el index porque ya lo dirigimos a través de las rutas

2022-05-17 23:07 UTC, BaltazarCortina1 requested changes

2022-05-17 23:07 UTC, BaltazarCortina1 commented on src/models/Employees.js
> +module.exports = mongoose.model('Employee', employeeSchema);
Mantengamos el formato del export que estaba antes
`export default mongoose.model('Employee', employeeSchema);`

2022-05-17 23:07 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +    }
Esta validacion esta de mas, si no le pasas un param no va a entrar en esta ruta

2022-05-17 23:07 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +      data: `Employee id: ${req.params.id} deleted.`,
Aca data deberia ser el recurso eliminado

2022-05-17 23:07 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +      data: undefined,
En data podrias pasarle el error, para tener mas informacion de que paso

2022-05-17 23:07 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +    }
Igual que en el anterior

2022-05-18 02:06 UTC, BaltazarCortina1 requested changes

2022-05-18 02:06 UTC, BaltazarCortina1 commented on src/index.js
> +import router from './routes/index';
Este import es el mismo que el de arriba

2022-05-18 02:09 UTC, cellamarematias commented on src/index.js
> +import router from './routes/index';
Esa línea está eliminada(3).. puede ser? Solo tengo esta: import router from './routes/index';

2022-05-18 02:12 UTC, BaltazarCortina1 commented on src/index.js
> +import router from './routes/index';
Tenes razon

2022-05-18 02:13 UTC, BaltazarCortina1 approved these changes

2022-05-18 02:13 UTC, merged