BaSP-TG-25: Get all employees and Get employees by ID
BaSP-m2022/balti-trackgenix-server pull request #19
Opened 2022-05-16 17:52 UTC by FlorenciaEusebi

2022-05-17 01:44 UTC, FefeTroanes requested changes

2022-05-17 15:55 UTC, FlorenciaEusebi commented on package.json
> +    "body-parser": "^1.20.0",
Listo, modificado :)

2022-05-17 18:26 UTC, ilcosme commented on src/index.js
>  app.get('/employees', getEmployeesById);
Flor si estas son las funciones que tenias que hacer vos deberías sacarlas del index general. Solo importarlas y usarlas en /routes/employees.js

2022-05-17 23:19 UTC, BaltazarCortina1 requested changes

2022-05-17 23:19 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +      data: {} || [] || undefined,
Aca deberias dejar solo undefined o directamente borrar la propiedad data

2022-05-17 23:19 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +    if (req.params.id) {
Esta validacion esta de mas, porque si no le pasas un param no entraria en esta ruta

2022-05-17 23:19 UTC, BaltazarCortina1 commented on src/index.js
>  } from './controllers/employees';
Esto no lo deberias usar aca

2022-05-17 23:19 UTC, BaltazarCortina1 commented on src/index.js
> +// app.delete('/employees', deleteEmployee);
Estas rutas no deberian estar aca, ya estan declaradas en `routes/employees.js`

2022-05-17 23:28 UTC, FlorenciaEusebi commented on src/controllers/employees.js
> +    if (req.params.id) {
Este comment es el unico que no entendi

2022-05-18 00:45 UTC, BaltazarCortina1 requested changes

2022-05-18 00:45 UTC, BaltazarCortina1 commented on src/routes/index.js
> +  .use('/employees', employeeRoutes);
Dejemos esto en una misma linea

2022-05-18 00:45 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +    if (req.params.id) {
Lo que quiero decir es que req.params.id siempre va a existir, porque para que una request entre en esta ruta le tenes que pasar si o si un id. Entonces siempre va a entrar en el if, por lo que la validacion en realidad no esta validando nada.
Podes borrar ese if, y el return que esta abajo con el mensaje `missing ID parameter`

2022-05-18 21:51 UTC, BaltazarCortina1 requested changes

2022-05-18 21:51 UTC, BaltazarCortina1 commented on src/models/Employees.js
> +    'projectId', Number,
Aca deberiamos dejar solo `Number`

2022-05-18 21:51 UTC, BaltazarCortina1 commented on src/controllers/employees.js
> +    });
Aca falta validar que realmente haya encontrado el employee

2022-05-19 19:47 UTC, BaltazarCortina1 approved these changes

2022-05-19 19:55 UTC, FefeTroanes approved these changes

2022-05-19 19:58 UTC, merged