Feature/tg-18-23/timesheets
BaSP-m2022/balti-trackgenix-server pull request #20
Opened 2022-05-16 20:54 UTC by FefeTroanes

2022-05-17 01:14 UTC, nicolascostanza commented on src/index.js
>  import {
Fede, aca debes borrar todos los imports y quedarte con el import de las funciones controladoras de timesheets pero en la carpeta de router/time-sheets.js

2022-05-17 01:17 UTC, nicolascostanza commented on src/controllers/time-sheets.js
> +    if (!result) {
creo este if no va a ingresar nunca, se va a ir al catch

2022-05-17 01:38 UTC, CamilaFigue submitted a review, later dismissed

2022-05-17 18:23 UTC, ilcosme commented on src/routes/time-sheets.js
> +router.put('/edit/:id', validateTimeSheetUpdate, editTimeSheet);
Fede creo que acá la ruta directamente puede ser una '/' para el método post. y '/:id' para el método put. No hace falta incluir add ni edit.

2022-05-18 00:09 UTC, BaltazarCortina1 requested changes

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/validations/time-sheets.js
> +// eslint-disable-next-line import/prefer-default-export
Eliminemos este comentario

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/models/Time-sheets.js
> +    default: () => Date.now(),
Eliminemos esto y agreguemoslo a la validacion de joi

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    return res.status(500).json({
Cambiemos el status code por un 400

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    if (req.params.id) {
Esta validacion es innecesaria, si no le pasas un param no entraria en esta ruta

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +      });
Falta validar que realmente haya encontrado el timesheet

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +      message: 'Id does not exist',
Si el id no existe en realidad no entra al catch. El mensaje aca deberia ser mas generico, porque es para cualquier cosa que genere un error inesperado

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    }
Igual que el de arriba

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    });
Igual que el de arriba

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +      });
Igual que el de arriba

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    if (!result) {
Esta validacion esta bien, si no encuentra el timesheet `result` va a ser `undefined` y va a entrar

2022-05-18 00:09 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    }
Lo mismo que en los de arriba

2022-05-18 15:24 UTC, FefeTroanes commented on src/index.js
>  import {
Lesto 👌🏼

2022-05-18 15:26 UTC, FefeTroanes commented on src/controllers/time-sheets.js
> +    if (!result) {
👌🏼

2022-05-18 15:43 UTC, FefeTroanes commented on src/index.js
> +// app.get('/time-sheets/get-all-time-sheets-by-employee/:id', getAllTimeSheetsByEmployee);
👌🏼

2022-05-18 16:29 UTC, FefeTroanes commented on src/controllers/time-sheets.js
> +      });
Esto por alguna razon no lo tengo en mi repo local

2022-05-18 16:30 UTC, FefeTroanes commented on src/controllers/time-sheets.js
> +    }
Aca entiendo que me estas diciendo el que mensaje de error deberia ser generico pero ahi no seria un error

2022-05-18 16:51 UTC, FefeTroanes commented on src/controllers/time-sheets.js
> +    return res.status(400).json({
👌🏼

2022-05-18 21:46 UTC, BaltazarCortina1 requested changes

2022-05-18 21:46 UTC, BaltazarCortina1 commented on src/routes/index.js
> +router.use('/time-sheets', timeSheetRouter);
La ruta deberia ser `/timesheets`

2022-05-18 21:46 UTC, BaltazarCortina1 commented on src/routes/time-sheets.js
> +const express = require('express');
Cambiemos este require por un import

2022-05-18 21:46 UTC, BaltazarCortina1 commented on src/validations/time-sheets.js
> +    rate: Joi.number(),
Tendrias que agregar date tambien aca

2022-05-18 21:46 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    return res.json({
En los ultimos dos catch falta el status code

2022-05-18 21:46 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    }
Esta validacion esta de mas

2022-05-18 21:46 UTC, BaltazarCortina1 commented on src/controllers/time-sheets.js
> +    }
No, aca es lo de la validacion que no va. `req.params.employee` siempre va a existir, sino no entraria a esta ruta

2022-05-19 03:40 UTC, FefeTroanes commented on src/controllers/time-sheets.js
> +    }
Ah esta, ahi saque esa y agregue una para que no tire el array vacio si es que el employee no existe

2022-05-19 20:13 UTC, BaltazarCortina1 approved these changes

2022-05-19 20:14 UTC, merged