BaSP-TG-14: admins
BaSP-m2022/balti-trackgenix-server pull request #21
Opened 2022-05-16 23:06 UTC by ilcosme

This is my request for merge to master branch. I made the neccessary functions to made possible to create, update, and delete an Admin, and to find and admin by the id. I also made the validations required and added the postman collection with the routes for testing.

2022-05-17 00:22 UTC, FlorenciaEusebi commented on src/controllers/admins.js
> +      msg: `No admin with the id of ${req.params.id}`,
Fer, creo que a este le falta el "data"

2022-05-18 00:18 UTC, BaltazarCortina1 requested changes

2022-05-18 00:18 UTC, BaltazarCortina1 commented on src/index.js
> +const routes = require('./routes/index');
Cambiemos este require por un import

2022-05-18 00:18 UTC, BaltazarCortina1 commented on src/controllers/admins.js
> +    } return res.status(400).json({
El `return` deberia estar el la siguiente linea, no en la misma que la `}`

2022-05-19 16:00 UTC, BaltazarCortina1 approved these changes

2022-05-19 16:00 UTC, merged