BaSP-TG-37: Tests timesheets
BaSP-m2022/balti-trackgenix-server pull request #33
Opened 2022-05-23 11:31 UTC by cellamarematias

2022-05-23 13:54 UTC, FefeTroanes commented on src/test/time-sheets.test.js
> +    const response = await request(app).get('/timesheet').send();
Hola Mati, aca la ruta esta distinta a proposito? Lo mismo en la linea 45

2022-05-23 13:57 UTC, cellamarematias commented on src/test/time-sheets.test.js
> +    const response = await request(app).get('/timesheet').send();
Hola Fede! Si, es para forzar el error. No sé si está bien pero se me ocurrió que podía ser así.

2022-05-23 14:22 UTC, nicolascostanza submitted a review, later dismissed

2022-05-23 14:22 UTC, nicolascostanza commented on src/seed/projects.js
> +}];
lo mismo, projects lo tiene cami y fer

2022-05-23 14:22 UTC, nicolascostanza commented on src/seed/tasks.js
> +  }];
lo mismo q los demas seed

2022-05-23 14:22 UTC, nicolascostanza commented on src/seed/time-sheets.js
> +}];
Aca tambien, debes traerte el seed de los compañeros

2022-05-23 14:41 UTC, cellamarematias commented on src/seed/projects.js
> +}];
Si Nico, los necesitaba para testear por eso los creé yo

2022-05-25 18:15 UTC, BaltazarCortina1 requested changes

2022-05-25 18:15 UTC, BaltazarCortina1 commented on src/test/time-sheets.test.js
> +  });
Este en realidad le esta pegando a `/timesheets/:id` y es similar al que esta abajo

2022-05-27 03:23 UTC, BaltazarCortina1 approved these changes

2022-05-27 03:24 UTC, merged