BaSP-TG-39: Superadmin tests
BaSP-m2022/balti-trackgenix-server pull request #34
Opened 2022-05-23 23:59 UTC by FefeTroanes

2022-05-24 01:17 UTC, cellamarematias commented on src/test/super-admins.test.js
> +  // Deberia actualizarlo? Es un string pero incluso en la documentacion de joy el metodo username
Si lo actualiza pero porque no está completa la validación.

2022-05-24 01:19 UTC, cellamarematias commented on src/test/super-admins.test.js
> +  // En el test que sigue no estoy muy seguro si tendria que recibir status 400 o 404
400: Para cuando una request está mal hecha, por ejemplo, falta un dato al actualizar un Super-Admin.
404: Para cuando no existe el recurso indicado, por ejemplo, cuando se quiere eliminar un Super-Adminque no existe en Base de Datos.

2022-05-24 02:29 UTC, nicolascostanza requested changes

2022-05-24 02:29 UTC, nicolascostanza commented on src/test/super-admins.test.js
> +    expect(response.body.data.length).toBeGreaterThan(0);
Aca fede pondria expect y verificaría el mensaje de correcto sea igual al de la controladora. A su vez sacaría la linea 19 y la haría en otro test pq estas testeeando "otra variante"

2022-05-24 02:29 UTC, nicolascostanza commented on src/test/super-admins.test.js
> +    expect(response.body.data.length).not.toBe(null);
Este expect de la linea 96 lo dejaria en otro test para tener un poco mas de especificidad si llega a fallar algun test. Ya que es "otra variante de testeo"

2022-05-24 02:29 UTC, nicolascostanza commented on src/test/super-admins.test.js
> +  test('response should return a 200 status', async () => {
el string de este test esta mal

2022-05-24 02:29 UTC, nicolascostanza commented on src/test/super-admins.test.js
> +  test('response should return a 200 status', async () => {
el string de este test es incorrecto

2022-05-25 01:32 UTC, BaltazarCortina1 requested changes

2022-05-25 01:32 UTC, BaltazarCortina1 commented on src/test/super-admins.test.js
> +/* eslint-disable no-useless-escape */
Este comment y las `\` antes de las `"` no son necesarios, los tests pasan igual

2022-05-25 01:32 UTC, BaltazarCortina1 commented on src/test/super-admins.test.js
> +// eslint-disable-next-line no-unused-vars
Este comment tampoco es necesario

2022-05-25 01:32 UTC, BaltazarCortina1 commented on src/test/super-admins.test.js
> +    expect(response.error).not.toBeTruthy();
Podes cambiar los `not.toBeTruthy` por `toBeFalsy`

2022-05-25 01:32 UTC, BaltazarCortina1 commented on src/test/super-admins.test.js
> +    expect(response.error).not.toBeTruthy();
Podrias validar que el superadmin que te trae es el que le pediste

2022-05-26 23:12 UTC, BaltazarCortina1 approved these changes

2022-05-26 23:13 UTC, merged