BaSP-TG-33: Seed, get all and create employees
BaSP-m2022/balti-trackgenix-server pull request #35
Opened 2022-05-24 00:25 UTC by nicolascostanza

I leave PR of my problem of week 10, carry out the seed of employees and test all the possible cases expected in the controller functions

2022-05-24 01:00 UTC, cellamarematias submitted a review, later dismissed

2022-05-24 02:32 UTC, nicolascostanza commented on src/test/employees.test.js
> +        expect(valuesFields[j]).not.toBe(null);
Listooo

2022-05-25 01:42 UTC, BaltazarCortina1 requested changes

2022-05-25 01:42 UTC, BaltazarCortina1 commented on src/models/Employees.js
> +    String,
Este model deberia tener las relaciones que hicimos entre los recursos. Fijate que debes haber partido de una version desactualizada de master

2022-05-25 01:42 UTC, BaltazarCortina1 commented on src/seed/employees.js
> +    mongoose.Types.ObjectId('628cf23dfb13310e147c4fdb')],
Cambia la indentacion de esta forma:
```suggestion
  assignedProjects: [
    mongoose.Types.ObjectId('628cf2442fed32f30b57dc75'),
    mongoose.Types.ObjectId('628cf23dfb13310e147c4fdb')
  ],
```
Lo mismo para el resto de los assignedProjects

2022-05-25 01:42 UTC, BaltazarCortina1 commented on src/test/employees.test.js
> +        expect(valuesFields[j]).not.toBe(null);
Esto es lo que hablamos en la pre-entrega. Por como esta planteado va a pasar aunque le falte alguna prop requerida. Por ahi es mejor testear que uno de la lista (puede ser el primero) tenga todas las props que deberia

2022-05-25 01:42 UTC, BaltazarCortina1 commented on src/test/employees.test.js
> +  });
Estos dos tests deberian ser uno, porque es el mismo caso

2022-05-27 16:07 UTC, BaltazarCortina1 approved these changes

2022-05-27 16:07 UTC, merged