BaSP-TG-36: Test projects - get one / update / delete
BaSP-m2022/balti-trackgenix-server pull request #36
Opened 2022-05-24 00:36 UTC by ilcosme

This is my request for merge to master branch. I made the testing functions necessary to test the projects resource. I tested the get one, update and delete functions developed by the team in last week assignment in both cases of success and error.

2022-05-24 02:38 UTC, nicolascostanza requested changes

2022-05-24 02:38 UTC, nicolascostanza commented on src/test/projects.test.js
> +});
Fer, te falta importar el modelo y seed de employee aca y tambien te faltan los de Admins, q no estan creados. Luego debes insertarlos adentro del before all como hiciste con los projects

2022-05-24 02:38 UTC, nicolascostanza commented on src/test/projects.test.js
> +    expect(response.body.data.length).not.toBe(null);
Acá pediría que me muestre el mensaje de éxito y no el tobe(null), el de null lo movería a otro test para agrupar casos de test correctamente

2022-05-24 02:38 UTC, nicolascostanza commented on src/test/projects.test.js
> +  test('Project updated', async () => {
Debes poner un describe por cada metodo que realices (get, post, delete, put) y luego realizar los test correspondientes a cada uno dentro

2022-05-24 02:38 UTC, nicolascostanza commented on src/test/projects.test.js
> +    expect(response.body.error).toBeFalsy();
Aca pediria el mensaje de exito al editar tambien !

2022-05-24 02:38 UTC, nicolascostanza commented on src/test/projects.test.js
> +  test('Project deleted', async () => {
Aca lo mismo, meter los test con metodo delete dentro de un describe

2022-05-25 02:04 UTC, BaltazarCortina1 requested changes

2022-05-25 02:04 UTC, BaltazarCortina1 commented on src/test/projects.test.js
> +describe('/GET /projects', () => {
Agregales que es el get por id -> `/GET /projects/:id`

2022-05-25 02:04 UTC, BaltazarCortina1 commented on src/test/projects.test.js
> +    expect(response.body.error).toBeFalsy();
Deberias verficar que el que te devuelve es el que le pediste

2022-05-27 14:10 UTC, BaltazarCortina1 approved these changes

2022-05-27 14:10 UTC, merged