BaSP-TG-35: Test projects - seed / get all / create
BaSP-m2022/balti-trackgenix-server pull request #37
Opened 2022-05-24 03:48 UTC by CamilaFigue

1. Seed created.
2. Get All test.
3. Create test.

2022-05-24 18:04 UTC, nicolascostanza commented on src/controllers/employees.js
> +    const result = await Employees.findByIdAndUpdate(req.params.id, (updatedEmployee)).populate('assignedProjects ');
Ojo el espacio aca en el populate

2022-05-24 19:08 UTC, FlorenciaEusebi commented on src/test/projects.test.js
> +  test('Should create an project successfully', async () => {
Esto es un error sin importancia, pero acá va A project en vez de AN

2022-05-25 02:20 UTC, BaltazarCortina1 requested changes

2022-05-25 02:20 UTC, BaltazarCortina1 commented on src/test/projects.test.js
> +describe('/GetAll /projects', () => {
Revisar formato de los describe

2022-05-25 02:20 UTC, BaltazarCortina1 commented on src/test/projects.test.js
> +  });
Este test basicamente esta contenido en el que sigue, porque si la response tiene lo que le mandaste significa que no es undefined

2022-05-25 02:20 UTC, BaltazarCortina1 commented on src/test/projects.test.js
> +    expect(response.body.data.client).toEqual('Camila Figueroa');
Aca deberias testear todas las propiedades que le mandaste, no solo algunas

2022-05-27 16:24 UTC, BaltazarCortina1 approved these changes

2022-05-27 16:24 UTC, merged