BaSP:TG-34: Tests employees - GET ONE/UPDATE/DELETE
BaSP-m2022/balti-trackgenix-server pull request #38
Opened 2022-05-24 12:45 UTC by AgustinFerrarello

At this time there only basic tests based on status codes, today i will add some more.

2022-05-24 14:24 UTC, ilcosme commented on src/test/employee.test.js
> +});
Agus podrias fijarte de matchear ademas del status code, el mensaje de error arrojado en cada caso y tambien el booleano error si quedo en false o true

2022-05-24 21:29 UTC, AgustinFerrarello commented on src/test/employee.test.js
> +});
Ahí agregué algunos tests en los mensajes de error o success

2022-05-25 02:29 UTC, BaltazarCortina1 requested changes

2022-05-25 02:29 UTC, BaltazarCortina1 commented on src/test/employee.test.js
> +  });
Cuando estas testeando un mismo caso, por ejemplo en estos dos, pone todos los expect dentro del mismo test.
Tambien podrias agregar un expect para el mensaje

2022-05-25 02:29 UTC, BaltazarCortina1 commented on src/test/employee.test.js
> +    expect(response.error).not.toBeFalsy();
Aca podrias cambiarlo por `toBeTruthy`

2022-05-25 02:29 UTC, BaltazarCortina1 commented on src/test/employee.test.js
> +  });
Aca, ademas de juntarlos, deberias agregar la validacion de que lo que te devuelve la request es lo que le mandaste para actualizar

2022-05-25 02:29 UTC, BaltazarCortina1 commented on src/test/employee.test.js
> +  });
Estos dos no son iguales?

2022-05-26 23:10 UTC, BaltazarCortina1 approved these changes

2022-05-26 23:10 UTC, merged