BaSP:TG-38: Tasks tests
BaSP-m2022/balti-trackgenix-server pull request #39
Opened 2022-05-24 23:41 UTC by Lucas-DeLorenzi

2022-05-25 02:41 UTC, BaltazarCortina1 requested changes

2022-05-25 02:41 UTC, BaltazarCortina1 commented on src/test/tasks.test.js
> +describe('GET all tasks', () => {
Revisar el formato de los describe

2022-05-25 02:41 UTC, BaltazarCortina1 commented on src/test/tasks.test.js
> +  });
Estos tests los podrias juntar en uno. Lo mismo para todos los que testean un mismo caso

2022-05-25 02:41 UTC, BaltazarCortina1 commented on src/test/tasks.test.js
> +  });
Aca lo mismo, si son el mismo caso deberian estar todos los expect en un mismo test.
En el ultimo expect, lo que te devuelve el servidor no es un array, asi que no deberias validar el length. Podrias validar que el id de la task que te devuelve es el que le pediste

2022-05-25 02:41 UTC, BaltazarCortina1 commented on src/test/tasks.test.js
> +    expect(response.body.data.date).not.toBeNull();
Aca deberias validar que sea la fecha correcta, no solo que no sea null

2022-05-25 02:41 UTC, BaltazarCortina1 commented on src/test/tasks.test.js
> +    done: false,
Deberia haber un caso en el que actualiza todos los campos que se pueden cambiar

2022-05-25 04:48 UTC, Lucas-DeLorenzi commented on src/test/tasks.test.js
> +describe('GET all tasks', () => {
hecho

2022-05-25 05:07 UTC, Lucas-DeLorenzi commented on src/test/tasks.test.js
> +  });
hecho

2022-05-25 05:07 UTC, Lucas-DeLorenzi commented on src/test/tasks.test.js
> +  });
hecho

2022-05-25 05:32 UTC, Lucas-DeLorenzi commented on src/test/tasks.test.js
> +    expect(response.body.data.date).not.toBeNull();
Lo había puesto de esa manera, porque la fecha no era requerida... Decidí sacarlo directamente

2022-05-25 18:08 UTC, BaltazarCortina1 requested changes

2022-05-25 18:08 UTC, BaltazarCortina1 commented on src/test/tasks.test.js
> +    done: true,
Al igual que en el update, deberia haber al menos un caso en el que creas una task con toda la data que puede tener

2022-05-27 00:14 UTC, Lucas-DeLorenzi commented on src/test/tasks.test.js
> +    done: false,
Ahí puse el caso en que se actualizan todos los campos posibles, descubrí que hay una restricción para modificar las propiedades employeeId y projectId, lo cual considero que seria un error, pero es algo que arrastramos de la semana pasada y no se si me corresponde modificarlo. Por esto, estas dos props no se pueden modificar

2022-05-27 00:19 UTC, Lucas-DeLorenzi commented on src/test/tasks.test.js
> +    done: true,
Ya está solucionado esto, agregué la propiedad Date que era la que faltaba. Pero también encontré un error en la función addTask de la carpeta controllers en el archivo tasks.js. Esta hecho el commit correspondiente.

2022-05-27 15:29 UTC, merged