BaSP-TG-32: Tests Admins
BaSP-m2022/balti-trackgenix-server pull request #40
Opened 2022-05-24 23:57 UTC by FlorenciaEusebi

2022-05-25 02:50 UTC, BaltazarCortina1 requested changes

2022-05-25 02:50 UTC, BaltazarCortina1 commented on src/seed/admins.js
> +  idEmployee: mongoose.Types.ObjectId('628cf218c545127e724c881c'),
Te falta agregar la propiedad `_id` en los seeds, por eso te fallan algunos de los tests

2022-05-25 02:50 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +  //   expect(response.body.message).toBe('Admin collected');
El mensaje "Admin collected" no esta en ningun lado, por eso falla. Ademas, la propiedad que viene en la respuesta es `msg`, no `message`

2022-05-25 02:50 UTC, BaltazarCortina1 commented on src/test/admins.test.js
>    });
Cuando testeas un mismo caso, deberias poner todos los expect en un mismo test

2022-05-25 02:50 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +    expect(response.body.msg).toEqual('Admin created successfully');
Falta validar que lo que te devuelve el server es lo mismo que le mandaste

2022-05-25 02:50 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +    expect(response.status).toBe(400);
Aca lo mismo que en el create

2022-05-28 18:32 UTC, BaltazarCortina1 requested changes

2022-05-28 18:32 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +    expect(response).toEqual(response);
Aca estas comparando la respuesta con la misma respuesta, no con lo que mandaste

2022-05-28 18:32 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +  // });
Este test deberia andar ahora

2022-05-28 18:32 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +    expect(response.status).toBe(400);
Aca sigue faltando verificar que devuelva lo mismo que le mandaste

2022-05-28 18:32 UTC, BaltazarCortina1 commented on src/test/admins.test.js
> +  // });
Este test tambien deberia andar ahora

2022-05-29 02:11 UTC, FlorenciaEusebi commented on src/test/admins.test.js
> +    expect(response.status).toBe(400);
No, para, este no, no tiene que devolver lo mismo que mande porque es error (no se logra updatear)

2022-05-29 18:26 UTC, BaltazarCortina1 approved these changes

2022-05-29 18:26 UTC, merged