BaSP-TG-90: Authentication middleware
BaSP-m2022/balti-trackgenix-server pull request #49
Opened 2022-06-26 22:41 UTC by Julian25

Work done on this branch:

- Created authentication middleware
- Applied authentication on admins routes
- updated admin controller

2022-06-27 03:42 UTC, nicomicheletti approved these changes

2022-06-27 12:28 UTC, lucasrendo commented on src/middlewares/authMiddleware.js
> +    return res.status(400)
Se que esteban mostraba un 400 pero no deberia ser un 401? (unauthorized)

2022-06-27 12:28 UTC, lucasrendo commented on src/middlewares/authMiddleware.js
> +        message: 'You need the role to access this route',
Esto es para el usuario por lo que no saben que significa 'the role' posiblemente. Tal vez un mensaje mas descriptivo seria: "You don't have permission to access this route", "Your credentials are missing a role", "No permissions specified for this account" o algo en esas lineas

2022-06-29 00:48 UTC, lucasrendo requested changes
- Hay una linea en el controller de Employee que no deberia estar. Este es el unico cambio necesario
- Opcionalmente seria bueno cambiar los codigos de los status

2022-06-29 00:48 UTC, lucasrendo commented on src/controllers/auth.js
> +    await firebaseApp.auth().setCustomUserClaims(newFirebaseEmployee.uid, { role: 'EMPLOYEE' });
Esto esta duplicado, ya esta en la linea 11

2022-06-29 00:48 UTC, lucasrendo commented on src/controllers/admins.js
> -      firebaseUid: newFirebaseUser.uid,
no implicaba menos codigo y mejor legibildad hacerlo de esta manera?

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/admins.js
> +    return res.status(401)
Seria un 403: prohibido, el usuario tiene un token de autenticacion pero no tiene un rol que le de permiso para ver el recurso donde intenta acceder

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/admins.js
> +    return res.status(401)
Nuevamente es un error 403

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/employees.js
> +    return res.status(401)
Status 403

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/employees.js
> +    return res.status(401)
Status 403

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/employees.js
> +    return res.status(401).json({
Aca tambien seria un 403 porque ya verificamos que existe un token anteriormente, por lo que tiene una "llave de autorizacion", simplemente no es una que le permita acceder al recurso.
En esencia la diferencia entre 401 y 403 es que en el 401 no existen credenciales para autenticar, en el 403 si existen pero no son validas, por lo que a razones practicas cualquier header con un token de acceso ya no puede ser un 401

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/super-admins.js
> +    return res.status(401)
status 403

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/super-admins.js
> +    return res.status(401)
stauts 403

2022-06-29 00:48 UTC, lucasrendo commented on src/middlewares/super-admins.js
> +    return res.status(401).json({
status 403

2022-06-29 01:27 UTC, lucasrendo approved these changes

2022-06-29 01:36 UTC, merged