BaSP-TG-09: Timesheet GET and DELETE
BaSP-m2022/balti-trackgenix-server pull request #6
Opened 2022-05-10 17:31 UTC by FlorenciaEusebi

2022-05-10 22:27 UTC, BaltazarCortina1 requested changes

2022-05-10 22:27 UTC, BaltazarCortina1 commented on src/index.js
> +import { deleteTs, getTs } from './resources/time-sheets';
Podemos cambiar `deleteTs `por `deleteTimesheets`? Y lo mismo en el get

2022-05-10 22:27 UTC, BaltazarCortina1 commented on src/resources/time-sheets.js
> +// Gets Single Time Sheet by Time Sheet ID
Los comentarios no son necesarios, el nombre de la funcion ya dice que hace

2022-05-10 22:27 UTC, BaltazarCortina1 commented on src/resources/time-sheets.js
> +    res.status(400).json({ msg: `No Time Sheet with the ID of ${req.params.id}` });
Revisa el formato de las respuestas que definimos en el doc de [definiciones generales](https://docs.google.com/document/d/1d_ywGx4RaSLIGdp8SVB_Hw-4pASdOamqz2zyF7pUd8M/edit?usp=sharing)

2022-05-10 22:27 UTC, BaltazarCortina1 commented on src/data/time-sheets.json
> +[{
No actualizaste el json con los cambios que habamos hoy

2022-05-10 23:59 UTC, FlorenciaEusebi commented on src/data/time-sheets.json
> +[{
Lo hice con Lucas, no se que habre tocado. Capaz nunca lo guarde :/

2022-05-11 01:16 UTC, BaltazarCortina1 approved these changes

2022-05-11 01:16 UTC, merged