BaSP-TG-07: Super-admins working fine
BaSP-m2022/balti-trackgenix-server pull request #8
Opened 2022-05-10 18:13 UTC by AgustinFerrarello

2022-05-10 22:52 UTC, BaltazarCortina1 requested changes

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/data/super-admins.json
> +[{"firstName":"agustin","lastName":"ferra","email":"rfarmiloe0@opensource.org","id":1},{"firstName":"Myrna","lastName":"Plainer","email":"mplaide2@tripod.com","id":3},{"firstName":"Madison","lastName
Podes formatear este json asi es mas facil ver las propiedades que tiene?

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/index.js
> +  addSA, findSA, delSA, editSA,
Podemos cambiar `addSA `por `addSuperAdmin`? Lo mismo con las otras funciones

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/index.js
> +  res.status(200).json({ data: sAdmins });
Move esta logica al archivo admin.js

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/resources/super-admins.js
> +const failSis = require('fs');
Podemos cambiar `failSis` por `fs`?

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/resources/super-admins.js
> +  superAd.push(newSA);
Te falta guardar el array modificado en el json

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/resources/super-admins.js
> +      msg: 'Please put a name, surname, email and id.',
Revisa el formato de las respuestas que definimos en el doc de [definiciones generales](https://docs.google.com/document/d/1d_ywGx4RaSLIGdp8SVB_Hw-4pASdOamqz2zyF7pUd8M/edit?usp=sharing). Lo mismo para todas las respuestas

2022-05-10 22:52 UTC, BaltazarCortina1 commented on src/resources/super-admins.js
> +  if (found) {
Aca no estas validando si realmente encontro uno que eliminar

2022-05-11 02:38 UTC, AgustinFerrarello commented on src/resources/super-admins.js
> +  superAd.push(newSA);
Listo

2022-05-11 02:38 UTC, AgustinFerrarello commented on src/resources/super-admins.js
> +const failSis = require('fs');
Listo

2022-05-11 02:38 UTC, AgustinFerrarello commented on src/index.js
> +  addSA, findSA, delSA, editSA,
Listo, también modifiqué a las otras funciones.

2022-05-11 02:39 UTC, AgustinFerrarello commented on src/index.js
> +  res.status(200).json({ data: sAdmins });
Listo

2022-05-11 02:45 UTC, AgustinFerrarello commented on src/resources/super-admins.js
> +  if (found) {
Acá no entendí bien, osea, la función elimina bien lo que le pido.

2022-05-12 02:53 UTC, BaltazarCortina1 requested changes

2022-05-12 02:53 UTC, BaltazarCortina1 commented on src/resources/super-admins.js
> +// const idFilter = (req) => (fSuperAd) => fSuperAd.id === parseInt(req.params.id, 10);
Elimina este comentario

2022-05-12 02:53 UTC, BaltazarCortina1 commented on src/resources/super-admins.js
> +    data: getAllSuperAdmin,
Aca deberias devolver el listado de super admins

2022-05-12 22:48 UTC, BaltazarCortina1 approved these changes

2022-05-12 22:48 UTC, merged